# Site settings
title: Chris Blog
SEOTitle: 杨佳欣的博客 | Chris Blog
header-img: img/post-bg-desk.jpg
email: 1752346954@qq.com
description: "Il n'ya qu'un héroïsme au monde : c'est de voir le monde tel qu'il est et de l'aimer."
keyword: "Chris, Chris Blog, 杨佳欣的博客, Yangjiaxin, 杨佳欣, iOS, Apple, iPhone, Java"
url: "https://github.com/Yangjiaxin121"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Yangjiaxin121/Yangjiaxin121.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "I'm trying!"
sidebar-avatar: /img/me.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     小过0.0
github_username:    Yangjiaxin121
facebook_username:  小过0.0
jianshu_username:   893073bb712a
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: ae8f570c37a04ea1e311                            #生成的clientID
  clientSecret: 24307cf7d69b6eab1a6695029405dde14e664533    #生成的clientSecret
  repo: yangjiaxin121.github.io    #仓库名称
  owner: Yangjiaxin121    #github用户名
  admin: Yangjiaxin121
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 2b5753c356c0058963e10f24b0618745

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "WY",
        href: "https://user.qzone.qq.com/1752346954/infocenter"
    },{
        title: "简书·Yangjiaxin",
        href: "http://www.jianshu.com/u/e71990ada2fd"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
